[pytest]
pythonpath = .

log_cli = true
log_cli_level = info
log_cli_format = [%(asctime)s][%(levelname)-8s][%(filename)s:%(lineno)d]: %(message)s

markers =
    stage_env: The Case only work in Dev, Uat, Pt environment.
    prod_env: The Case is Monitoring on PROD environment.
    
addopts = --alluredir=./allure-results --clean-alluredir --capture=no --allure-no-capture

filterwarnings =
    ignore::urllib3.exceptions.InsecureRequestWarning